name: CI
on: 
    pull_request:
      branches: [main]
    push:
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Nodejs
        uses: actions/checkout@v1
        with:
          node-version: "14.x"
      - run: npm ci 
      - run: npm run build
  
      