name: CI
on: 
    pull_request:
      branches: [main]
    push:
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Nodejs
        uses: actions/checkout@v1
        with:
          node-version: "12.x"
      - run: npm ci 
      - run: npm test -- -- coverage
        env:
          CI: true
      - name: build project
        if: github.event_nbame == 'push'
        run: npm run build
